name: Build and Test ISO

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            genisoimage \
            qemu-system-x86 \
            wget \
            unzip \
            grub-pc-bin \
            grub-efi-amd64-bin \
            initramfs-tools

      - name: Build ISO
        run: bash scripts/build-iso.sh

      - name: Check ISO exists and print size
        run: |
          if [ ! -f output/mikaos.iso ]; then
            echo "ISO not found!"
            exit 1
          fi
          ls -lh output/mikaos.iso

      - name: QEMU boot test (look for GRUB)
        run: |
          set -e
          timeout 20 qemu-system-x86_64 \
            -cdrom output/mikaos.iso \
            -nographic \
            -no-reboot \
            -serial mon:stdio \
            > qemu_output.txt 2>&1 || true

          # Change this string to something your ISO always outputs on successful boot (e.g., "MIKAOS", "GRUB", etc.)
          if grep -q "GRUB" qemu_output.txt; then
            echo "ISO booted and GRUB loaded successfully."
          else
            echo "ISO did not boot successfully (GRUB not found in output)!"
            cat qemu_output.txt
            exit 1
          fi

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: mikaos-iso
          path: output/mikaos.iso
