name: Build MikaOS

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y make xorriso p7zip-full
        
    - name: Build ISO
      run: make
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mikaos-iso
        path: output/mikaos.iso
