name: Build MIKAOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          make \
          xorriso \
          unzip \
          wget \
          grub-common \
          initramfs-tools \
          file \
          isomd5sum

    - name: Prepare directories
      run: |
        mkdir -p build/boot/grub
        mkdir -p output

    - name: Fetch and build
      run: |
        # Set permissions for scripts
        chmod +x scripts/*.sh
        
        # Run build process
        make all

    - name: Verify ISO
      run: |
        file output/mikaos.iso | grep "ISO 9660 CD-ROM"
        isoinfo -i output/mikaos.iso -R -l | grep "vmlinuz"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mikaos-iso
        path: output/mikaos.iso
        retention-days: 3
